apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: px-postgres-snap-clone
spec:
  storageClassName: px-repl3-sc-demotemp
  dataSource:
    name: px-postgres-snapshota
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi