apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: px-postgres-snapshot
spec:
  volumeSnapshotClassName: px-csi-snapclass-demotemp
  source:
    persistentVolumeClaimName: px-postgres-pvc